import type { CollectionConfig } from 'payload'

export const Coupons: CollectionConfig = {
  slug: 'coupons',
  admin: {
    useAsTitle: 'code',
    defaultColumns: ['code', 'discountType', 'discountValue', 'isActive', 'usageCount'],
    description: '🎟️ Discount Coupons for loyal customers. These can be auto-generated by the system.',
  },
  access: {
    read: ({ req: { user } }) => Boolean(user), // Restrict read to authenticated users. Validation should be done via a custom backend API if needed.
    create: ({ req: { user } }) => Boolean(user), 
    update: ({ req: { user } }) => Boolean(user), 
    delete: ({ req: { user } }) => Boolean(user),
  },
  fields: [
    {
      name: 'code',
      type: 'text',
      required: true,
      unique: true,
      label: 'Coupon Code (e.g. VIP20)',
    },
    {
      name: 'discountType',
      type: 'select',
      required: true,
      defaultValue: 'percentage',
      options: [
        { label: 'Percentage (%)', value: 'percentage' },
        { label: 'Fixed Amount (₹)', value: 'fixed' },
      ],
    },
    {
      name: 'discountValue',
      type: 'number',
      required: true,
      label: 'Discount Value',
      admin: {
        description: 'If type is Percentage, 10 means 10%. If Fixed, 500 means ₹500 off.',
      },
    },
    {
      name: 'isActive',
      type: 'checkbox',
      defaultValue: true,
      label: 'Is Active?',
    },
    {
      name: 'validUntil',
      type: 'date',
      label: 'Valid Until (Expiration Date)',
      admin: {
        date: {
          pickerAppearance: 'dayAndTime',
        }
      }
    },
    {
      name: 'usageLimit',
      type: 'number',
      defaultValue: 1,
      label: 'Maximum Usage Limit',
      admin: {
        description: 'How many times can this coupon be used in total? Set to 1 for one-time generated loyalty coupons.',
      },
    },
    {
      name: 'usageCount',
      type: 'number',
      defaultValue: 0,
      admin: {
        readOnly: true,
      },
      label: 'Current Usage Count',
    },
    {
      name: 'customerEmail',
      type: 'text',
      label: 'Assigned Customer Email (Optional)',
      admin: {
        description: 'If filled, this coupon can only be used by this email address.',
      }
    }
  ],
}
